apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metal3
resources:
- ../../keepalived

secretGenerator:
- name: ironic-ca-cert
  files:
  - tls.crt=ironic-ca.crt
- name: ironic-inspector-ca-cert
  files:
  - tls.crt=ironic-inspector-ca.crt
- name: ironic-cert
  files:
  - tls.crt=ironic.crt
  - tls.key=ironic.key
  type: "kubernetes.io/tls"
- name: ironic-inspector-cert
  files:
  - tls.crt=ironic-inspector.crt
  - tls.key=ironic-inspector.key
  type: "kubernetes.io/tls"
- name: mariadb-ca-cert
  files:
  - tls.crt=mariadb-ca.crt
- name: mariadb-cert
  files:
  - tls.crt=mariadb.crt
  - tls.key=mariadb.key
  type: "kubernetes.io/tls"

patchesStrategicMerge:
- tls.yaml
